context:
  version: "0.38.3"

package:
  name: ncc
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@vercel/ncc/-/ncc-${{ version }}.tgz
  sha256: c9f9d715af74152fd248220a43a2a09868fdab68f7438dd558bbb69aa487bb86

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - ncc --help 2>&1 | grep -q "Usage: "ncc <cmd> <opts>\""

about:
  license: MIT
  license_file:
    - LICENSE
  summary: Simple CLI for compiling a Node.js module into a single file, together with all its dependencies, gcc-style.
  homepage: https://github.com/vercel/ncc
  repository: https://github.com/vercel/ncc

extra:
  recipe-maintainers:
    - danielnachun
